- name: Check if fail2ban is running
  hosts: all
  tasks:
    - name: Check if fail2ban is running
      command: systemctl status fail2ban
      ignore_errors: yes
      changed_when: false
      register: service_fail2ban_status
    - name: Report status of fail2ban
      fail:
        msg: |
          Service fail2ban is not running.
          Output of `systemctl status fail2ban`:
          {{ service_fail2ban_status.stdout }}
          {{ service_fail2ban_status.stderr }}
        when: service_fail2ban_status | failed
